# for live server
routes:
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /:
    data: post.home
    template: home

# for local server
# routes:
#     /signup/: members\signup
#     /signin/: members\signin
#     /account/: members\account

collections:
  /post/:
    permalink: /post/{slug}/
    template: index
  /:
      permalink: /{slug}/
      template: home

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
